# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  pigeon:
    cmds:
      - dart run pigeon --input pigeons/recorder.dart

  release:
    cmds:
      - flutter pub publish
